version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NAV_READ_PACKAGES }}

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    open-pull-requests-limit: 20
    registries: '*'
    groups:
      aksel-dependencies:
        patterns:
          - '@navikt/aksel*'
          - '@navikt/ds*'
      react-dependencies:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
