name: label-dependabot-pr
on:
  pull_request:
    types: [opened, unlabeled]

jobs:
  label-dependabot-pr:
    uses: navikt/flex-github-actions-workflows/.github/workflows/label-dependabot-pr.yml@master
    permissions:
      pull-requests: write
